#!/bin/sh

# Start Thinkpad OSD daemon
#if [ -x /usr/bin/tpb ] &&  [ -w /dev/nvram ] && [ -r /dev/nvram ]; then
#    /usr/bin/tpb -d
#fi

xmodmap ~/.Xmodmap &
nm-applet &
xscreensaver &

#exec fluxbox
exec fluxbox -log "~/.fluxbox/log"

